import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import YAML from "yaml";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(SCRIPT_DIR, "..");
const DEFAULT_COPY_FILE = path.join(ROOT_DIR, "copy", "ru.yml");
const DEFAULT_OUTPUT_FILE = path.join(ROOT_DIR, "src", "generatedCopy.ts");
const DEFAULT_UI_FILE = path.join(ROOT_DIR, "src", "ui.html");

const COPY_START_MARKER = "<!-- @generated-copy:start -->";
const COPY_END_MARKER = "<!-- @generated-copy:end -->";

function buildTypeScriptModule(copy) {
  const serialized = JSON.stringify(copy, null, 2);
  return `// This file is generated by scripts/generate-copy.mjs.
// Do not edit it by hand. Edit copy/ru.yml, then run npm run build.

export const COPY = ${serialized} as const;

export type CopyTree = typeof COPY;
`;
}

function buildUiCopyScript(copy) {
  const uiCopy = { ui: copy.ui };
  return `<script>window.UI_COPY = ${JSON.stringify(uiCopy)};</script>`;
}

async function injectUiCopy(uiFile, uiCopyScript) {
  const html = await readFile(uiFile, "utf8");
  const startIndex = html.indexOf(COPY_START_MARKER);
  const endIndex = html.indexOf(COPY_END_MARKER);

  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) {
    throw new Error(
      `Missing copy markers in ${path.relative(ROOT_DIR, uiFile)}. ` +
        `Expected ${COPY_START_MARKER} and ${COPY_END_MARKER}.`
    );
  }

  const before = html.slice(0, startIndex + COPY_START_MARKER.length);
  const after = html.slice(endIndex);
  const nextHtml = `${before}\n${uiCopyScript}\n${after}`;

  if (nextHtml !== html) {
    await writeFile(uiFile, nextHtml, "utf8");
  }
}

export async function generateCopy({
  copyFile = DEFAULT_COPY_FILE,
  outputFile = DEFAULT_OUTPUT_FILE,
  uiFile = DEFAULT_UI_FILE,
} = {}) {
  const rawYaml = await readFile(copyFile, "utf8");
  const copy = YAML.parse(rawYaml);

  if (!copy || typeof copy !== "object") {
    throw new Error(`Invalid copy file: ${path.relative(ROOT_DIR, copyFile)}`);
  }

  await mkdir(path.dirname(outputFile), { recursive: true });
  await writeFile(outputFile, buildTypeScriptModule(copy), "utf8");
  await injectUiCopy(uiFile, buildUiCopyScript(copy));

  return { copy, outputFile, uiFile };
}

const isCliRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isCliRun) {
  const { outputFile, uiFile } = await generateCopy();
  console.log(`Generated ${path.relative(ROOT_DIR, outputFile)} and updated ${path.relative(ROOT_DIR, uiFile)}.`);
}
